# Fazit {#conclusion}

Abschließend kann festgehalten werden, dass die Erkenntnisse meiner Bachelorarbeit auch für den Gold-Bonder gelten. 
So steigt die Wahrscheinlichkeit eines Gate-Durchbruchs mit einer Erhöhung der Bondparamter. 
Dabei hat die Ultraschallleistung den größten Effekt. 

Die Schichtdicke von Chrom hat keinen großen Einfluss auf die Wahrscheinlichkeit eines Gate-Durchbruchs. 
Die Schichtdicke von Gold dagegen, weißt einen messbaren Effekt auf: 
Durch eine Erhöhung der Schichtdicke, steigt die Wahrscheinlichkeit eines Gate-Durchbruchs. 
Dieses Ergebnis stimmt zwar mit meiner Bachelorarbeit überein, kann allerdings nicht erklärt werden.

Meine abschließende Empfehlung ist daher: 
Um einen Gate-Durchbruch möglichst zu vermeiden, sollte der Gold-Bonder verwendet werden. 
Dieser bietet im Vergleich zum Aluminium-Bonder den Vorteil, dass an ihm mit geringeren Paramterwerten (vor Allem geringerer Ultraschallleistung) gebondet werden kann.

Zusätzlich deuten bisher alle Messungen darauf hin, dass eine Erhöhung der Schichtdicke der Bondpads die Wahrscheinlichkeit eines Gatedurchbruchs nicht reduziert. 
Im Gegenteil scheinen dickere Goldschichten die Wahrscheinlichkeit zu erhöhen. 
Dies steht nicht im Einklang mit der Literatur und kann derzeit nicht eindeutig erklärt werden. 
Möglicherweise zeigt sich ein positiver Effekt erst bei drastisch erhöhten Schichtdicken (Gold > 400 nm).
Dies ist aus kostengründen allerdings nicht relevant und wurde daher nicht weiter verfolgt.

*Benutzt den Goldbonder!*
