---
title: Mock Experiment
subtitle: Analysis Script
author: Konstantin Schneider
---

```{r include = FALSE, purl=FALSE}
knitr::opts_chunk$set(
  comment = "#>", 
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  error = FALSE
)
```

```{r echo = FALSE}
#####################################################
###                                               ###
###   File created automatically. Do not change!  ###
###   Changes will be overwritten!                ###
###                                               ###
#####################################################
```


## Load custom functions

```{r}
source(here::here("R/custom_functions.R"))
```

## Load packages

```{r}
library(tidyverse)
library(lubridate)
```

## Read and wrangle data
### Cr/Au

```{r}
files <- list.files(
  here::here("data-raw/gatebreak/mock/cr_au")
)

data_crau <-
  tibble(
    filename = files,
    type = rep(c("blind", "sample"), each = 3, times = 4),
    chip = rep(1:4, each = 6),
    rep = rep(1:3, times = 8)
  ) |>
  mutate(
    measurement = map(
      filename,
      ~read_csv(
        here::here("data-raw/gatebreak/mock/cr_au", .),
        skip = 8
      ) |>
        select(
          amps = "Reading",
          volts = "Value",
          date = "Date",
          time = "Time"
        ) |>
        mutate(
          date = dmy(date) + hms(time),
          volts = round(volts, digits = 1)
        ) |>
        select(-time)
    )
  ) |>
  select(-filename) |>
  unnest(measurement) |>
  group_by(chip, rep) |>
  nest(measurement = c("amps", "volts")) |>
  ungroup()


data_mock <-
  data_crau
```

```{r purl = FALSE}
data_mock |> head()
```

## Plots

```{r}
plot_crau_kennlinie <-
  data_crau |>
  mutate(index = row_number()) |>
  mutate(
    chip = str_glue("Chip: {chip}") |>
      as_factor()
  ) |>
  filter(type == "sample") |>
  unnest(measurement) |>
  ggplot(
    aes(
      x = volts,
      y = amps * 10^6,
    )
  ) +
  geom_line(
    aes(
      colour = as.factor(rep),
      group = index
    )
  ) +
  scale_colour_brewer(palette = "Set1") +
  labs(
    colour = "Rep.",
    x = "Spannung in Volt",
    y = "Stromstärke in µA"
  ) +
  facet_wrap(
    facets = vars(chip)
  )
```

```{r purl = FALSE}
plot_crau_kennlinie
```

```{r}
plot_crau_blind <-
  data_crau |>
  ungroup() |>
  filter(type == "blind") |>
  unnest(measurement) |>
  group_by(volts) |>
  summarise(amps = mean(amps)) |>
  ggplot(
    aes(
      x = volts,
      y = amps * 10^6
    )
  ) +
  geom_line() +
  labs(
    colour = "Rep.",
    x = "Spannung in Volt",
    y = "Stromstärke in µA"
  )
```

```{r purl = FALSE}
plot_crau_blind
```

## Save data

```{r}
fs::dir_create(
  path = c(
    here::here("data/doe"),
    here::here("data/gatebreak")
  ),
  recurse = TRUE
)

write_rds(
  x = data_mock,
  file = here::here("data/gatebreak/gb_mock.rds")
)

save(
  plot_crau_kennlinie,
  plot_crau_blind,
  file = here::here("data/gatebreak/gb_mock_plots.rda")
)
```
